// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: proto/todo.proto

package todo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoSvrClient is the client API for TodoSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoSvrClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoReq, opts ...grpc.CallOption) (*CreateTodoRsp, error)
}

type todoSvrClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoSvrClient(cc grpc.ClientConnInterface) TodoSvrClient {
	return &todoSvrClient{cc}
}

func (c *todoSvrClient) CreateTodo(ctx context.Context, in *CreateTodoReq, opts ...grpc.CallOption) (*CreateTodoRsp, error) {
	out := new(CreateTodoRsp)
	err := c.cc.Invoke(ctx, "/funstar.server.todo.TodoSvr/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoSvrServer is the server API for TodoSvr service.
// All implementations must embed UnimplementedTodoSvrServer
// for forward compatibility
type TodoSvrServer interface {
	CreateTodo(context.Context, *CreateTodoReq) (*CreateTodoRsp, error)
	mustEmbedUnimplementedTodoSvrServer()
}

// UnimplementedTodoSvrServer must be embedded to have forward compatible implementations.
type UnimplementedTodoSvrServer struct {
}

func (UnimplementedTodoSvrServer) CreateTodo(context.Context, *CreateTodoReq) (*CreateTodoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodo not implemented")
}
func (UnimplementedTodoSvrServer) mustEmbedUnimplementedTodoSvrServer() {}

// UnsafeTodoSvrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoSvrServer will
// result in compilation errors.
type UnsafeTodoSvrServer interface {
	mustEmbedUnimplementedTodoSvrServer()
}

func RegisterTodoSvrServer(s grpc.ServiceRegistrar, srv TodoSvrServer) {
	s.RegisterService(&TodoSvr_ServiceDesc, srv)
}

func _TodoSvr_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoSvrServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/funstar.server.todo.TodoSvr/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoSvrServer).CreateTodo(ctx, req.(*CreateTodoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoSvr_ServiceDesc is the grpc.ServiceDesc for TodoSvr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoSvr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "funstar.server.todo.TodoSvr",
	HandlerType: (*TodoSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoSvr_CreateTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todo.proto",
}
