// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: proto/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthSvrClient is the client API for AuthSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthSvrClient interface {
	// 登录鉴权
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRsp, error)
}

type authSvrClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthSvrClient(cc grpc.ClientConnInterface) AuthSvrClient {
	return &authSvrClient{cc}
}

func (c *authSvrClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRsp, error) {
	out := new(LoginRsp)
	err := c.cc.Invoke(ctx, "/funstar.server.auth.AuthSvr/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthSvrServer is the server API for AuthSvr service.
// All implementations must embed UnimplementedAuthSvrServer
// for forward compatibility
type AuthSvrServer interface {
	// 登录鉴权
	Login(context.Context, *LoginReq) (*LoginRsp, error)
	mustEmbedUnimplementedAuthSvrServer()
}

// UnimplementedAuthSvrServer must be embedded to have forward compatible implementations.
type UnimplementedAuthSvrServer struct {
}

func (UnimplementedAuthSvrServer) Login(context.Context, *LoginReq) (*LoginRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthSvrServer) mustEmbedUnimplementedAuthSvrServer() {}

// UnsafeAuthSvrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthSvrServer will
// result in compilation errors.
type UnsafeAuthSvrServer interface {
	mustEmbedUnimplementedAuthSvrServer()
}

func RegisterAuthSvrServer(s grpc.ServiceRegistrar, srv AuthSvrServer) {
	s.RegisterService(&AuthSvr_ServiceDesc, srv)
}

func _AuthSvr_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvrServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/funstar.server.auth.AuthSvr/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvrServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthSvr_ServiceDesc is the grpc.ServiceDesc for AuthSvr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthSvr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "funstar.server.auth.AuthSvr",
	HandlerType: (*AuthSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthSvr_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
